<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DxfCoordinateExtractor</RootNamespace>
    <AssemblyName>DxfCoordinateExtractor</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="netDxf" Version="2023.11.10" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
